url: https://courses.stolley.co
baseurl: /te/

timezone: America/Chicago

course:
  number: COM 425/529
  title: Technical Editing
  uid: te
  tagline: >
    Online course covering theory and principles of editing through intensive applied practice.
  term: Spring 2021
  # Set `days: ""` (empty string) for weekly/asynchronous classes
  days: ""
  license:
    name: Creative Commons
    url: https://creativecommons.org/licenses/by/4.0/
  instructor:
    honorific: Dr.
    name: Karl Stolley
    title: Professor
    full_title: Associate Professor of Digital Writing & Rhetoric
    url: https://stolley.co/
    github: https://github.com/karlstolley/
    email: kstolley@iit.edu
    office_hours: >
      Office hours via Basecamp Chat or Pings on <b>Tuesdays, 4pm to 5pm</b> Central Time
      (America/Chicago), or by appointment or chance. If you’d like to audio or video chat, we can
      of course do that, too. Just message me first. I’m always signed into Basecamp and closely
      monitor my notifications. Message or email any time—I make students a priority, and I will
      respond as soon as I am able.
  navigation:
    - label: Calendar
      href: "#this-week" # Stock for policies, projects.
      id: cal # read this into SCSS somehow?
    - label: Basecamp
      href: "https://3.basecamp.com/3058761/projects/19831928"
      id: bcp
    - label: Projects
      href: "projects/#current" # Stock for policies, projects.
      id: pro # read this into SCSS somehow?
    - label: Policies
      href: "policies/" # Stock for policies, projects.
      id: pol # read this into SCSS somehow?
  css:
    font-url: "https://use.typekit.net/qqk1feg.css"
    theme: winter

collections_dir: syllabus

collections:
  weeks:
  projects:
  policies:
    # Rearrange the files listed here to change their order on the policies page.
    # To remove a section from the policies page, you *must* delete the file in the
    # /syllabus/_policies/ directory
    order:
      - description.md
      - goals.md
      - books.md
      - materials.md
      - special-needs.md
      - participation.md
      - assignment-submission.md
      - late-work.md
      - grading-policy.md
      - grading-criteria.md
      - technology-policy.md
      - academic-integrity.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-open-course

exclude:
  - backstop_data
  - backstop.json
  - exe
  - lib
  - Rakefile
  - "*.gemspec"
